#!/usr/bin/python3

import socket


ip = input("Digite o ip alvo: \r\n")
porta = int(input("Digite a porta alvo: \r\n"))

meusocket = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
meusocket.connect((ip,porta))
resp = meusocket.recv(1024)
print(resp)
